<?php
namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DiscussCategoriesTableSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();

        $categories = [
            [
                'title' => 'Annonces',
                'slug' => 'annonces',
                'description' => 'Toutes les annonces à propos de Division.',
                'color' => '#0D9691',
                'icon' => 'fas fa-bullhorn',
                'conversation_count' => 1,
                'last_conversation_id' => null,
                'is_locked' => true,
                'level' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Général',
                'slug' => 'general',
                'description' => 'Tout ce qui tourne autour de ARK en général.',
                'color' => '#19cabb',
                'icon' => 'fas fa-toolbox',
                'conversation_count' => 0,
                'last_conversation_id' => null,
                'is_locked' => false,
                'level' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Mods',
                'slug' => 'mods',
                'description' => 'Tout ce qui concerne les mods sur ARK.',
                'color' => '#4bbf49',
                'icon' => 'fas fa-code',
                'conversation_count' => 0,
                'last_conversation_id' => null,
                'is_locked' => false,
                'level' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Serveurs Dédiés',
                'slug' => 'serveursdedies',
                'description' => 'Une question sur la configuration d\'un serveur dédié ? C\'est ici !',
                'color' => '#b93d6a',
                'icon' => 'fas fa-wrench',
                'conversation_count' => 0,
                'last_conversation_id' => null,
                'is_locked' => false,
                'level' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Feedback',
                'slug' => 'feedback',
                'description' => 'Envie de donner un feedback sur le site, les serveurs, le discord ? C\'est ici !',
                'color' => '#9354CA',
                'icon' => 'fas fa-comment-dots',
                'conversation_count' => 0,
                'last_conversation_id' => null,
                'is_locked' => false,
                'level' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Aberration',
                'slug' => 'aberration',
                'description' => 'Discussions à propos de la map Aberration.',
                'color' => '#aa8ed6',
                'icon' => 'fas fa-globe-europe',
                'conversation_count' => 0,
                'last_conversation_id' => null,
                'is_locked' => false,
                'level' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Crystal Isles',
                'slug' => 'crystalisles',
                'description' => 'Discussions à propos de la map Crystal Isles.',
                'color' => '#7c7c7c',
                'icon' => 'fas fa-globe-asia',
                'conversation_count' => 0,
                'last_conversation_id' => null,
                'is_locked' => false,
                'level' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Extinction',
                'slug' => 'extinction',
                'description' => 'Discussions à propos de la map Extinction.',
                'color' => '#55acee',
                'icon' => 'fas fa-globe-americas',
                'conversation_count' => 0,
                'last_conversation_id' => null,
                'is_locked' => false,
                'level' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Genesis',
                'slug' => 'genesis',
                'description' => 'Discussions à propos de la map Genesis.',
                'color' => '#dd2e44',
                'icon' => 'fas fa-globe-africa',
                'conversation_count' => 0,
                'last_conversation_id' => null,
                'is_locked' => false,
                'level' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Ragnarok',
                'slug' => 'ragnarok',
                'description' => 'Discussions à propos de la map Ragnarok.',
                'color' => '#c1694f',
                'icon' => 'fas fa-globe-europe',
                'conversation_count' => 0,
                'last_conversation_id' => null,
                'is_locked' => false,
                'level' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Scorched Earth',
                'slug' => 'scorchedearth',
                'description' => 'Discussions à propos de la map Scorched Earth.',
                'color' => '#fdcb58',
                'icon' => 'fas fa-globe-asia',
                'conversation_count' => 0,
                'last_conversation_id' => null,
                'is_locked' => false,
                'level' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'The Center',
                'slug' => 'thecenter',
                'description' => 'Discussions à propos de la map The Center.',
                'color' => '#ffac33',
                'icon' => 'fas fa-globe-americas',
                'conversation_count' => 0,
                'last_conversation_id' => null,
                'is_locked' => false,
                'level' => 12,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'The Island',
                'slug' => 'theisland',
                'description' => 'Discussions à propos de la map The Island.',
                'color' => '#2f2f2f',
                'icon' => 'fas fa-globe-africa',
                'conversation_count' => 0,
                'last_conversation_id' => null,
                'is_locked' => false,
                'level' => 13,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Valguero',
                'slug' => 'valguero',
                'description' => 'Discussions à propos de la map Valguero.',
                'color' => '#78b159',
                'icon' => 'fas fa-globe-europe',
                'conversation_count' => 0,
                'last_conversation_id' => null,
                'is_locked' => false,
                'level' => 14,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Hors Sujet',
                'slug' => 'horssujet',
                'description' => 'Rien à voir avec ARK ? Poste le ici !',
                'color' => '#1977ca',
                'icon' => 'fas fa-quote-right',
                'conversation_count' => 0,
                'last_conversation_id' => null,
                'is_locked' => false,
                'level' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ];

        DB::table('discuss_categories')->insert($categories);
    }
}
