language: php

php:
  - 7.2
  - 7.3

env:
  matrix:
    - DB=mysql
  global:
    - DEFAULT=1

services:
  - redis-server
  - mysql

matrix:
  fast_finish: true

  allow_failures:
    - php: 7.2
      env: COVERALLS=1 DEFAULT=0 DB=mysql

  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=0
    - php: 7.2
      env: COVERALLS=1 DEFAULT=0 DB=mysql

before_install: echo 'extension="redis.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE xetaravel_test;'; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then composer require --dev php-coveralls/php-coveralls; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then mkdir -p build/logs; fi"
  - phpenv rehash
  - set +H
  - mysql -V

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then vendor/bin/phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=PSR2 ./app ./routes ./tests; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then php vendor/bin/php-coveralls -c .coveralls.yml -v; fi"

notifications:
  email: false
